# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetario', '0002_auto_20160109_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='unidad',
        ),
        migrations.AddField(
            model_name='receta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='receta',
            name='preparacion',
            field=models.TextField(),
        ),
    ]
